name: mkdocs-build

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 allow pushing to gh-pages

jobs:
  build:
    name: Build and Deploy MkDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: mkdocs build --config-file mkdocs.yml --site-dir site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
